### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by icespite** [Ice-Hazymoon/163_daka#2]
打卡失败 RequestError: Error: connect ECONNREFUSED 127.0.0.1:443
    at new RequestError (C:\Users\LENOVO\Desktop\163_daka-master\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\LENOVO\Desktop\163_daka-master\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\LENOVO\Desktop\163_daka-master\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\LENOVO\Desktop\163_daka-master\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (C:\Users\LENOVO\Desktop\163_daka-master\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'RequestError',
  message: 'Error: connect ECONNREFUSED 127.0.0.1:443',
  cause: Error: connect ECONNREFUSED 127.0.0.1:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443
  },

**Comment by Ice-Hazymoon** [comment]
是否开启过代理

**Comment by icespite** [comment]
> 是否开启过代理

一直开着v2

**Comment by icespite** [comment]
> 是否开启过代理

我放到服务器运行成功了，感谢
