### ISSUE TITLE
登录失败 code 250

### ISSUE THREAD

**Issue by lazy-bum** [Ice-Hazymoon/163_daka#6]
{ message: '当前登录失败，请稍后再试', code: 250 }

**Comment by jiaton** [comment]
The same problem happened to me.

**Comment by monsterxcn** [comment]
The same problem happened to me.

就从6天前开始出现这个问题。部分报错信息：

```
{ message: '当前登录失败，请稍后再试', code: 250 }
打卡失败 TransformError: TypeError: Cannot read property 'map' of undefined
    at new TransformError (/home/runner/work/163_daka/163_daka/node_modules/request-promise-core/lib/errors.js:50:15)
    at /home/runner/work/163_daka/163_daka/node_modules/request-promise-core/lib/plumbing.js:118:41
    at tryCatcher (/home/runner/work/163_daka/163_daka/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/163_daka/163_daka/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/163_daka/163_daka/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/163_daka/163_daka/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/163_daka/163_daka/node_modules/bluebird/js/release/promise.js:725:18)
```

我是用 GitHub Action 执行的，所以这几天的日志都在。7天之前都是正常的，日志：[7 days ago](https://github.com/monsterxcn/163_daka/runs/1109826409?check_suite_focus=true)，6天前开始出现此错误：[6 days ago](https://github.com/monsterxcn/163_daka/runs/1115292184?check_suite_focus=true)
